/** Filter sections (PublicAPI CompanyFilterController, GblFilterSection). */
export const FILTER_SECTIONS = [
  "billRuns",
  "companyInbox",
  "companyInvoices",
  "companyLogs",
  "companyNotifications",
  "companyUpcomingSchedule",
  "creditNotes",
  "customers",
  "externalInvoices",
  "externalOrders",
  "historyRatePlan",
  "internalCompanyRequests",
  "invoices",
  "orders",
  "paymentRuns",
  "productRatePlans",
  "products",
  "subscriptionRatePlan",
  "subscriptions",
  "subscriptionsv2",
  "transactions",
  "upsCapitalClaims",
  "upsCapitalShipping",
] as const;

/** Operator display names (for rules). */
export const OPERATOR_DISPLAY_NAMES = [
  "after",
  "before",
  "between",
  "contains",
  "contains_only",
  "current_week",
  "does_not_include",
  "empty",
  "equals",
  "greater_than",
  "greater_than_equal",
  "includes",
  "is",
  "is_not",
  "last_15_days",
  "last_30_days",
  "last_3_months",
  "last_6_months",
  "last_7_days",
  "last_month",
  "less_than",
  "less_than_equal",
  "next_30_days",
  "next_60_days",
  "next_7_days",
  "next_90_days",
  "not_contains",
  "not_empty",
  "not_equals",
  "starts_with",
  "this_month",
  "today",
  "tomorrow",
  "yesterday",
] as const;

export type FilterSection = (typeof FILTER_SECTIONS)[number];
export type OperatorDisplayName = (typeof OPERATOR_DISPLAY_NAMES)[number];
